version: '2.1'
services:
  base:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - REDIS_URL=redis://redis:6379

  executor:
    extends: base
    volumes:
      - .:/app
    command: bash
    tty: true
    ports:
      - "5500:5500"
    links:
      - redis

  redis:
    mem_limit: 32m
    image: redis:alpine
