version: '2.1'
services:
  base:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    environment:
      - LOG_LEVEL=${LOG_LEVEL}

  executor:
    extends: base
    volumes:
      - .:/app
    command: bash
